language: node_js
node_js:
  - node
matrix:
  allow_failures:
  - node_js: node
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: coloursummarizer
  skip_cleanup: true

script:
  - echo No tests
