language: node_js
node_js:
- node
matrix:
  allow_failures:
  - node_js: node
deploy:
  provider: s3
  access_key_id: "AKIAIUBNK2PBU4GISDVA"
  secret_access_key:  "ulSnEJzZeJxuDFCKvD8MGKpeHwRQdA4wiLCFGMiRObhubgtvDutHzsMtiuJnbarLCXmDRrOv5lFgTqa/DQDr33lOvRu3M2K8sROGlIxXmOo6f6dZWxjxVtjjjQK5RnOlxzL3gjazw9+7lkVpvcakZwjxKWeVvGI/z9SF33s4sETEnlVGrnHR8FTnNT0yj3ZXPgaK0luqng57CgjiemSqWaXzEStDna+PKN/hozcRa31Tp2/keP2KXPhyEG37h614fEFAkZJS4CUifFIKUv6YH7lBMOohERqWcgvOPwnuzlxmOsuhMT0imbYSY51xcx9P4IhZF1AAdburwP0mkOn3DXvlBjyg067ZhqVHtIE6354bpfRYHAB3cwzRSiguyKSPPGeDaJjZlE9AQR5xPfupPLFp/konTnX8V/97a4UAZuwfG87R2FVGIuUzic5x/yH+NBZAUjpLV9d0/pMs89wIKdCLlGOcrsjBKV+Wt5ZOmRJFpCiWb0Cav7EXVMctudpDn5SSi6hWXHKGCNRE8cmpCGphx1IcxUhuPjEvVDTa81JghgIIOocqHO7ZCU0uPdB6WfoRnvPBiTtQqOd2iuLvP8SpZXr+NFBNkFCAXaAgiamlQmWYhy/yTHo0fRMFoHNJ+8mYnFr22ydEywPQurv98hWsix9vgM8L0+Ew8SPYq0w="
  bucket: "coloursummarizer"
  skip_cleanup: true
  script:
- echo No tests
